apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-shared-rwx
  namespace: flink
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

